# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Add comment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, '[질문]') }}
    permissions:
      issues: write
    steps:
      # - name: Add reactions
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     comment-id: ${{github.event.comment.id}}
      #     reactions: rocket
      - name: Find Comment
        uses: peter-evans/find-comment@v1.3.0
        id: fc
        with:
          issue-number: 1
          body-includes: ${{ github.event.comment.body }}
      - run : |
          echo ${{ steps.fc.outputs.comment-id }}
          echo ${{ steps.fc.outputs.comment-body }}
          echo ${{ steps.fc.outputs.comment-author }}
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: 2
          body: |
            ${{ github.event.comment.body }}