# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Add comment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  issue_commented:
    name: Issue comment
    # Run this job only for none pr comments
    # if: ${{ !github.event.issue.pull_request }} 
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1.3.0
        id: fc
        with:
          issue-number: 2
          body-includes: ${{ github.event.comment.body }}
          comment-author: kimhanui
      # - name: Create or Update Comment
      #   uses: peter-evans/create-or-update-comment@v1.4.5
      #   with:
      #     issue-number: 2
      #     body: |
      #       ${{ github.event.comment.body }}
            